# config.yaml
model:
  name: "ResUnet"
  in_channels: 4
  out_channels: 9
  n_filters: 64


data:
  data_directory: '../dataset/1.0.0/'
  original_classes: [0,1,2,3,4,5,6,7,8,9]
  classes_to_background: [0, 1]
  batch_size: 16
  worker_count: 0
  worker_buffer_size: 0
  shard_bool: True
  class_names: ['no_data', 'clouds', 'artificial surfaces and construction ', 'cultivated areas', 'broadleaf tree cover', 'coniferous tree cover', 'herbaceous vegetation', 'natural material surfaces', 'permanent snow-covered surfaces', 'water bodies']

training:
  num_epochs: 20
  learning_rate: 0.0001
  weight_decay: 0.0001

optimizer:
  name: "adamw"

loss:
  name: "focal_loss"
  class_frequencies: [0.00000000e+00, 1.70447610e-05, 5.03171731e-02, 3.34047791e-01, 2.28628355e-01, 7.96288181e-02, 2.75100100e-01, 8.06214221e-03, 8.84316184e-07, 2.41976915e-02]
  class_weights_mode: "log_inverse_frequency"
  recalculate_class_frequencies: False
  weights_normalization_method: "sum_to_one"

logging:
  outputs_dir: "outputss/logs"
  max_to_keep: 5



seed: 274