# config.yaml
model:
  name: "ResUnet"
  in_channels: 4
  out_channels: 9
  n_filters: 64


data:
  data_directory: '../dataset/1.0.0/'
  original_classes: [0,1,2,3,4,5,6,7,8,9]
  classes_to_background: [0, 1]
  batch_size: 16
  worker_count: 0
  worker_buffer_size: 0
  shard_bool: True

training:
  num_epochs: 5
  learning_rate: 0.0001
  weight_decay: 0.0001

optimizer:
  name: "adamw"

loss:
  name: "weighted_bce_loss"
  class_weights: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.2, 0.1, 0.1]  # Adjust based on your number of classes

logging:
  log_dir: "outputs/logs"
  checkpoint_dir: "outputs/checkpoints"
  max_to_keep: 5



seed: 274